### ISSUE TITLE
Timer starts at "43:00:00"

### ISSUE THREAD

**Issue by JamoCA** [narduz86/jquery-tinytimer#3] opened 2017-03-17 14:10 UTC
In v0.0.0 (dated 3/17/2017), the timer starts at "43:00:00" instead of "00:00:00".  I've tried using both regular & minified distribution versions.  I've also set `{timerCounter:0}` and used the zero() function... and it's set to "43:00:00".

**Comment by narduz86** [comment] 2017-03-30 17:41
Duplicate of #2, should be solved in current version. Please confirm. 
If not, please give  me more details. I'm still learning how to deal with versioning, your "0.0.0" is older than current one for sure.

**Comment by JamoCA** [comment] 2017-04-17 17:03
I had downloaded it from GitHub the same day I reported the issue. I just redownloaded it today (4/17/2017) and encounter the same same issue.  Even no options are passed ($("#my-div").timer();), it still starts at "43:00:00".  I'm using Firefox Developer, but it also does this in Chrome, Edge & IE (Windows 10).

**Comment by narduz86** [comment] 2017-04-20 13:38
Thank you for the feedback, I'll try to reproduce and fix the issue!

**Comment by saurabhmage** [comment] 2018-04-30 15:59
@narduz86  did you find any soluction ..

I am also facing same issue

**Comment by saurabhmage** [comment] 2018-05-03 06:04
@narduz86 @JamoCA 

Found solution:
replace line //
var f = new Date( this.counter + ( new Date() ).getTimezoneOffset() * 60000 );
with twon lines.. 
                   
 var d = new Date( 'Thu Jan 01 1970 00:00:00');

var f = new Date( this.counter +  d.getTimezoneOffset() * 60000 );

**Comment by narduz86** [comment] 2018-05-06 21:22
Sorry for the long absence from the project. Thanks saurabhmage, your solution works fine for me as well, clearly the time zone has to be teken from the correct date, which actually is  Jan 01 1970 00:00:00.

**Comment by narduz86** [comment] 2018-05-06 21:33
I close the issue, thanks to @saurabhmage

**Closed as completed by narduz86** 2018-05-06 21:33 UTC
